import { describe, it, expect, jest, beforeEach } from '@jest/globals';

jest.unstable_mockModule('../config/environment.js', () => ({
  __esModule: true,
  config: {
    port: 3001,
    pdf: { tempDir: '/tmp/pdf', tempPublicBaseUrl: '/tmp-pdf' },
  },
}));

jest.unstable_mockModule('../utils/logger.js', () => ({
  __esModule: true,
  default: { info: jest.fn(), warn: jest.fn(), error: jest.fn() },
}));

jest.unstable_mockModule('../database/models.js', () => ({
  __esModule: true,
  getCompanyModel: jest.fn(async () => ({
    findOne: () => ({ lean: async () => null }),
  })),
}));

jest.unstable_mockModule('../pdf/generator.service.js', () => ({
  __esModule: true,
  default: { generateFromHtml: jest.fn() },
}));

jest.unstable_mockModule('./storage-path.service.js', () => ({
  __esModule: true,
  storagePathService: {
    ensureCompanyStructure: jest.fn(),
    getModulePath: jest.fn(() => '/tmp/out'),
  },
}));

const loadSubject = async () => import('./dispatch-note-document.service.js');

const buildData = (overrides: Record<string, unknown> = {}) => ({
  header: {
    companyName: 'TEST COMPANY',
    companySubtitle: 'Planta de Asfalto',
    logoUrl: '',
    accentColor: '#10B981',
  },
  dispatch: {
    valeNumber: '20260707-1810',
    dispatchDate: '07/07/26',
    customerName: 'Constructora Andina del Sur S.A.C. (CASUR)',
    projectName: 'Renovación vial Urbanización Mayorazgo',
    materialName: 'Mezcla asfáltica MAC-2',
    quantityLabel: '52.5',
    plate: 'AZJ-910',
    driverName: 'Luis Quispe',
    driverPhone: '979555214',
    dispatchHour: '18:10',
    notes: 'Unidad 1',
    unitLabel: 'Unidad 1',
    ...((overrides.dispatch as Record<string, unknown>) || {}),
  },
  footer: { generatedBy: 'Generated by TEST COMPANY' },
  ...overrides,
});

describe('renderDispatchNoteHtml (vale premium media A4)', () => {
  beforeEach(() => jest.clearAllMocks());

  it('renderiza los datos del despacho con el acento de la company', async () => {
    const { renderDispatchNoteHtml } = await loadSubject();

    const html = renderDispatchNoteHtml(buildData(), 'http://127.0.0.1:3001');

    expect(html).toContain('20260707-1810');
    expect(html).toContain('AZJ-910');
    expect(html).toContain('52.5');
    expect(html).toContain('18:10');
    expect(html).toContain('Constructora Andina del Sur S.A.C. (CASUR)');
    expect(html).toContain('Renovación vial Urbanización Mayorazgo');
    expect(html).toContain('Luis Quispe');
    expect(html).toContain('979555214');
    // Acento dinámico de la company, nunca el rojo/gris del vale viejo.
    expect(html).toContain('#10B981');
    expect(html).not.toContain('#ef3c2d');
    expect(html).not.toContain('dotted');
  });

  it('ocupa media A4 con línea de corte y permite wrap acotado en cliente/obra', async () => {
    const { renderDispatchNoteHtml } = await loadSubject();

    const html = renderDispatchNoteHtml(buildData(), 'http://127.0.0.1:3001');

    expect(html).toContain('height: 148.5mm');
    expect(html).toContain('cut-line');
    // Cliente/obra multi-línea sin romper el layout: clamp a 2 líneas.
    expect(html).toContain('-webkit-line-clamp: 2');
    expect(html).toContain('overflow-wrap: break-word');
  });

  it('acento inválido cae al color por defecto (nunca inyecta CSS)', async () => {
    const { renderDispatchNoteHtml } = await loadSubject();

    const html = renderDispatchNoteHtml(
      buildData({ header: { companyName: 'X', accentColor: 'red; } body{display:none}' } }),
      'http://127.0.0.1:3001'
    );

    expect(html).not.toContain('display:none');
    expect(html).toContain('#1a2b23');
  });

  it('incluye el QR solo cuando generate pasa el dataURL', async () => {
    const { renderDispatchNoteHtml } = await loadSubject();

    const withQr = renderDispatchNoteHtml(buildData(), 'http://x', {
      verificationUrl: 'https://lila/files/vale.pdf',
      qrDataUrl: 'data:image/png;base64,QR',
    });
    const withoutQr = renderDispatchNoteHtml(buildData(), 'http://x');

    expect(withQr).toContain('data:image/png;base64,QR');
    expect(withQr).toContain('Verificar vale');
    expect(withoutQr).not.toContain('Verificar vale');
  });

  it('omite celular/unidad vacíos y no duplica la nota que ya es la unidad', async () => {
    const { renderDispatchNoteHtml } = await loadSubject();

    const html = renderDispatchNoteHtml(
      buildData({ dispatch: { driverPhone: '', unitLabel: '', notes: 'Descargar en km 12+400' } }),
      'http://x'
    );

    expect(html).not.toContain('CEL.');
    expect(html).not.toContain('UNIDAD<');
    expect(html).toContain('Descargar en km 12+400');
  });

  it('escapa HTML en los campos capturados en campo', async () => {
    const { renderDispatchNoteHtml } = await loadSubject();

    const html = renderDispatchNoteHtml(
      buildData({ dispatch: { customerName: '<script>alert(1)</script>' } }),
      'http://x'
    );

    expect(html).not.toContain('<script>alert(1)</script>');
    expect(html).toContain('&lt;script&gt;');
  });
});
