import { DocumentSchema } from './types';

/**
 * Schema definition for Control de Imprimacion (CTL-IMP).
 */
export const controlImprimacionSchema: DocumentSchema = {
  id: 'control-imprimacion',
  code: 'CTL-IMP',
  name: 'Control de Imprimacion',
  description: 'Protocolo de riego de imprimacion, control de tasa y panel fotografico.',
  category: 'Quality',
  version: '1.1.0',
  lastUpdated: '2026-03-29',
  orientation: 'landscape',
  pageSize: 'A4',
  margins: { top: 10, right: 10, bottom: 10, left: 10 },
  sections: [
    {
      id: 'header',
      type: 'header',
      pageOrientation: 'landscape',
      headerConfig: {
        logoKey: 'header.logoUrl',
        leftTextKey: 'header.companyName',
        centerLines: ['REGISTRO', 'CONTROL DE CALIDAD', 'PROTOCOLO DE RIEGO DE IMPRIMACION'],
        rightFields: [
          { label: 'CODIGO', key: 'header.codigo' },
          { label: 'VERSION', key: 'header.version' },
          { label: 'FECHA', key: 'header.fecha' },
          { label: 'FOLIO', key: 'header.pagina' },
        ],
      },
    },
    {
      id: 'identificacion',
      type: 'simpleFields',
      title: '1. Identificacion',
      pageOrientation: 'landscape',
      gridColumns: 4,
      fields: [
        { key: 'proyecto.obra', label: 'PROYECTO', type: 'text', span: 4, required: true },
        { key: 'proyecto.ubicacion', label: 'UBICACION', type: 'text', span: 2 },
        { key: 'proyecto.descripcion', label: 'DESCRIPCION', type: 'text', span: 2 },
        { key: 'proyecto.documentoReferencia', label: 'DOCUMENTO DE REFERENCIA', type: 'text', span: 2 },
        { key: 'header.fecha', label: 'FECHA', type: 'date', span: 2 },
      ],
    },
    {
      id: 'materialesInsumos',
      type: 'dataTable',
      title: '2. Control de Calidad - Materiales e Insumos',
      pageOrientation: 'landscape',
      dynamicRows: false,
      columns: [
        { key: 'item', label: 'Item', type: 'number', width: 60, align: 'center', editable: false },
        { key: 'tipoLigante', label: 'Tipo de Ligante', type: 'text', width: 140, align: 'center', editable: true, placeholder: 'Ej: MC-30' },
        { key: 'criteriosAceptacion', label: 'Criterios de Aceptacion', type: 'text', width: 260, align: 'left', editable: true, placeholder: 'Ingrese el criterio de aceptacion' },
        { key: 'conforme', label: 'Conforme', type: 'checkbox', width: 70, align: 'center', exclusiveGroup: 'materialesConformidad' },
        { key: 'noConforme', label: 'No Conforme', type: 'checkbox', width: 90, align: 'center', exclusiveGroup: 'materialesConformidad' },
        { key: 'nia', label: 'N/A', type: 'checkbox', width: 60, align: 'center', exclusiveGroup: 'materialesConformidad' },
        { key: 'fabricante', label: 'Fabricante', type: 'text', width: 120, align: 'center', group: 'Certificado de Calidad', editable: true, placeholder: 'Ingrese fabricante' },
        { key: 'fecha', label: 'Fecha', type: 'date', width: 110, align: 'center', group: 'Certificado de Calidad', editable: true },
        { key: 'certificado', label: 'Nro Certificado', type: 'text', width: 150, align: 'center', group: 'Certificado de Calidad', editable: true, placeholder: 'Ingrese Nro Certificado' },
      ],
    },
    {
      id: 'controlRiego',
      type: 'dataTable',
      title: '3. Control de Calidad - Riego de Imprimacion',
      pageOrientation: 'landscape',
      dynamicRows: false,
      columns: [
        { key: 'item', label: 'Item', type: 'number', width: 60, align: 'center', editable: false },
        { key: 'requerimientos', label: 'Requerimientos', type: 'text', width: 200, align: 'left', editable: true },
        { key: 'resultadoObtenido', label: 'Resultado Obtenido', type: 'text', width: 200, align: 'left', editable: true, placeholder: 'Ingrese resultado obtenido' },
        { key: 'criteriosAceptacion', label: 'Criterios de Aceptacion', type: 'text', width: 260, align: 'left', editable: true },
        { key: 'conforme', label: 'Conforme', type: 'checkbox', width: 70, align: 'center', exclusiveGroup: 'riegoConformidad' },
        { key: 'noConforme', label: 'No Conforme', type: 'checkbox', width: 90, align: 'center', exclusiveGroup: 'riegoConformidad' },
        { key: 'nia', label: 'N/A', type: 'checkbox', width: 60, align: 'center', exclusiveGroup: 'riegoConformidad' },
        { key: 'responsable', label: 'Responsable', type: 'text', width: 140, align: 'center', group: 'Registro de Pruebas / Ensayos', editable: true, placeholder: 'Ingrese responsable' },
        { key: 'fecha', label: 'Fecha', type: 'date', width: 110, align: 'center', group: 'Registro de Pruebas / Ensayos', editable: true },
        { key: 'observaciones', label: 'Observaciones', type: 'text', width: 160, align: 'left', group: 'Registro de Pruebas / Ensayos', editable: true, placeholder: 'Ingrese observaciones' },
      ],
    },
    {
      id: 'documentacionAdjunta',
      type: 'dataTable',
      title: '4. Documentacion Adjunta',
      pageOrientation: 'landscape',
      dynamicRows: false,
      columns: [
        { key: 'item', label: 'Item', type: 'number', width: 60, align: 'center', editable: false },
        { key: 'descripcion', label: 'Descripcion', type: 'text', width: 240, align: 'left', editable: true },
        { key: 'si', label: 'Si', type: 'checkbox', width: 60, align: 'center', exclusiveGroup: 'docAdjunta' },
        { key: 'no', label: 'No', type: 'checkbox', width: 60, align: 'center', exclusiveGroup: 'docAdjunta' },
        { key: 'nia', label: 'N/A', type: 'checkbox', width: 60, align: 'center', exclusiveGroup: 'docAdjunta' },
        { key: 'observaciones', label: 'Observaciones', type: 'text', width: 200, align: 'left', editable: true, placeholder: 'Ingrese observaciones' },
      ],
    },
    {
      id: 'observacionesProtocolo',
      type: 'richText',
      title: '5. Observaciones y/o Comentarios',
      pageOrientation: 'landscape',
      placeholder: 'Ingrese observaciones y/o comentarios',
    },
    {
      id: 'firmasProtocolo',
      type: 'signatures',
      title: 'Firmas',
      signatureStyle: 'line',
      pageOrientation: 'landscape',
      signatures: [
        { key: 'elaboradoPor', label: 'ELABORADO POR', sublabel: 'Responsable', required: true, showCIP: true },
        { key: 'revisadoPor', label: 'REVISADO POR', sublabel: 'Responsable', required: true, showCIP: true },
        { key: 'aprobadoPor', label: 'APROBADO POR', sublabel: 'Responsable', required: true, showCIP: true },
      ],
    },
    {
      id: 'tasaIdentificacion',
      type: 'simpleFields',
      title: 'Registro de Control de Tasa de Riego de Imprimacion',
      pageOrientation: 'landscape',
      pageBreakBefore: true,
      includeHeader: true,
      headerOverride: {
        centerLines: [
          'REGISTRO',
          'CONTROL DE CALIDAD',
          'REGISTRO DE CONTROL DE TASA DE RIEGO DE IMPRIMACION',
        ],
      },
      gridColumns: 4,
      fields: [
        { key: 'proyecto.obra', label: 'PROYECTO', type: 'text', span: 4, placeholder: 'Ingrese nombre del proyecto' },
        { key: 'proyecto.ubicacion', label: 'UBICACION', type: 'text', span: 2, placeholder: 'Ingrese ubicacion' },
        { key: 'proyecto.descripcion', label: 'DESCRIPCION', type: 'text', span: 2, placeholder: 'Ingrese descripcion' },
        { key: 'proyecto.documentoReferencia', label: 'DOCUMENTO DE REFERENCIA', type: 'text', span: 2, placeholder: 'Ingrese documento de referencia' },
        { key: 'header.fecha', label: 'FECHA', type: 'date', span: 2 },
        { key: 'header.codigo', label: 'Nro REGISTRO', type: 'text', span: 2, placeholder: 'Ingrese Nro de registro' },
      ],
    },
    {
      id: 'tasaControl',
      type: 'simpleFields',
      title: 'Control de la Tasa de Imprimacion - Emulsion de Imprimacion',
      pageOrientation: 'landscape',
      gridColumns: 4,
      fields: [
        { key: 'tasa.materialBituminoso', label: 'Tipo de Material Bituminoso', type: 'text', span: 2, placeholder: 'Ej: Liquido Asfaltico MC-30' },
        { key: 'tasa.gravedadEspecifica', label: 'Gravedad especifica', type: 'number', span: 2, placeholder: 'Ej: 1.00' },
        { key: 'tasa.loteProduccion', label: 'Lote de Produccion', type: 'text', span: 2, placeholder: 'Ingrese lote de produccion' },
        { key: 'tasa.certificadoCalidad', label: 'Nro Certificado de Calidad', type: 'text', span: 2, placeholder: 'Ingrese Nro de certificado' },
        { key: 'tasa.temperaturaAtmosferica', label: 'Temperatura Atmosferica', type: 'number', span: 2, placeholder: 'Ej: 24.5' },
        { key: 'tasa.temperaturaLigante', label: 'Temperatura de Ligante', type: 'number', span: 2, placeholder: 'Ej: 65.0' },
      ],
    },
    {
      id: 'tasaRegistroDatos',
      type: 'dataTable',
      title: 'Registro de Datos',
      pageOrientation: 'landscape',
      dynamicRows: false,
      columns: [
        { key: 'descripcion', label: 'Registro de Datos', type: 'text', width: 260, align: 'left', editable: false },
        { key: 'a', label: 'A', type: 'number', width: 90, align: 'right', editable: true, placeholder: 'Ingrese A' },
        { key: 'b', label: 'B', type: 'number', width: 90, align: 'right', editable: true, placeholder: 'Ingrese B' },
        { key: 'c', label: 'C', type: 'number', width: 90, align: 'right', editable: true, placeholder: 'Ingrese C' },
        { key: 'unidad', label: 'Unidad', type: 'text', width: 90, align: 'center', editable: false },
        { key: 'observaciones', label: 'Observaciones', type: 'text', width: 160, align: 'left', editable: true, placeholder: 'Ingrese observaciones' },
      ],
    },
    {
      id: 'resultadoInspeccion',
      type: 'dataTable',
      title: 'Resultado de la Inspeccion',
      pageOrientation: 'landscape',
      dynamicRows: false,
      columns: [
        { key: 'resultado', label: 'Resultado de la Inspeccion', type: 'text', width: 320, align: 'left', editable: true },
        { key: 'conforme', label: 'Conforme', type: 'checkbox', width: 80, align: 'center', exclusiveGroup: 'resultadoConformidad' },
        { key: 'noConforme', label: 'No Conforme', type: 'checkbox', width: 90, align: 'center', exclusiveGroup: 'resultadoConformidad' },
        { key: 'nia', label: 'N/A', type: 'checkbox', width: 60, align: 'center', exclusiveGroup: 'resultadoConformidad' },
        { key: 'observaciones', label: 'Observaciones', type: 'text', width: 200, align: 'left', editable: true },
      ],
    },
    {
      id: 'observacionesTasa',
      type: 'richText',
      title: 'Observaciones y/o Comentarios',
      pageOrientation: 'landscape',
      placeholder: 'Ingrese observaciones y/o comentarios',
    },
    {
      id: 'firmasTasa',
      type: 'signatures',
      title: 'Firmas',
      signatureStyle: 'line',
      pageOrientation: 'landscape',
      signatures: [
        { key: 'elaboradoPor', label: 'ELABORADO POR', sublabel: 'Responsable', required: true, showCIP: true },
        { key: 'revisadoPor', label: 'REVISADO POR', sublabel: 'Responsable', required: true, showCIP: true },
        { key: 'aprobadoPor', label: 'APROBADO POR', sublabel: 'Responsable', required: true, showCIP: true },
      ],
    },
    {
      id: 'registroFotografico',
      type: 'photoPanel',
      title: 'Panel Fotografico',
      pageOrientation: 'portrait',
      pageBreakBefore: true,
      includeHeader: true,
      headerOverride: {
        centerLines: ['REGISTRO', 'CONTROL DE CALIDAD', 'PANEL FOTOGRAFICO'],
      },
      maxImages: 20,
      layout: '2x3',
      showFecha: true,
      showProgresiva: true,
    },
  ],
  defaultData: {
    header: {
      logoUrl: '',
      companyName: '',
      codigo: '',
      version: '',
      fecha: '',
      pagina: '1-1',
      correlativo: '',
    },
    proyecto: {
      obra: '',
      contratista: '',
      subcontratista: '',
      ubicacion: '',
      descripcion: '',
      documentoReferencia: '',
    },
    materialesInsumos: [
      {
        key: 'certificadoCalidad',
        item: 1,
        tipoLigante: '',
        criteriosAceptacion: '',
        conforme: false,
        noConforme: false,
        nia: false,
        fabricante: '',
        fecha: '',
        certificado: '',
      },
    ],
    controlRiego: [
      {
        key: 'inspeccionSuperficie',
        item: 1,
        requerimientos: 'Inspeccion de superficie existente',
        resultadoObtenido: '',
        criteriosAceptacion:
          'La base granular debera encontrarse liberada. Los resultados de la Prueba de Densidad de Campo y el Control Topografico deberan cumplir lo indicado en las Especificaciones Tecnicas y planos aprobados del proyecto. La superficie a imprimar debera estar seca, limpia, libre de suciedad, elementos sueltos u otro material objetable.',
        conforme: false,
        noConforme: false,
        nia: false,
        responsable: '',
        fecha: '',
        observaciones: '',
      },
      {
        key: 'temperaturaAtmosferica',
        item: 2,
        requerimientos: 'Temperatura atmosferica',
        resultadoObtenido: '',
        criteriosAceptacion: 'Minimo 6 C',
        conforme: false,
        noConforme: false,
        nia: false,
        responsable: '',
        fecha: '',
        observaciones: '',
      },
      {
        key: 'temperaturaAplicacion',
        item: 3,
        requerimientos: 'Temperatura de aplicacion',
        resultadoObtenido: '',
        criteriosAceptacion: 'Minimo 50 C / Maximo 70 C',
        conforme: false,
        noConforme: false,
        nia: false,
        responsable: '',
        fecha: '',
        observaciones: '',
      },
      {
        key: 'tasaImprimacion',
        item: 4,
        requerimientos: 'Control de tasa de imprimacion',
        resultadoObtenido: '',
        criteriosAceptacion: 'Tasa de aplicacion de 0.8 a 1.2 (L/m2)',
        conforme: false,
        noConforme: false,
        nia: false,
        responsable: '',
        fecha: '',
        observaciones: '',
      },
      {
        key: 'curado',
        item: 5,
        requerimientos: 'Curado',
        resultadoObtenido: '',
        criteriosAceptacion: 'La capa de riego de imprimacion se ha curado sin ser alterada',
        conforme: false,
        noConforme: false,
        nia: false,
        responsable: '',
        fecha: '',
        observaciones: '',
      },
    ],
    documentacionAdjunta: [
      {
        key: 'certificadoCalidad',
        item: 1,
        descripcion: 'Certificado de Calidad',
        si: false,
        no: false,
        nia: false,
        observaciones: '',
      },
      {
        key: 'registroTasa',
        item: 2,
        descripcion: 'Registro de Control de Tasa de Riego de Imprimacion',
        si: false,
        no: false,
        nia: false,
        observaciones: '',
      },
      {
        key: 'otro',
        item: 3,
        descripcion: 'Otro',
        si: false,
        no: false,
        nia: false,
        observaciones: '',
      },
    ],
    observacionesProtocolo: '',
    firmasProtocolo: {
      elaboradoPor: { nombre: '', cargo: 'Responsable', cip: '' },
      revisadoPor: { nombre: '', cargo: 'Responsable', cip: '' },
      aprobadoPor: { nombre: '', cargo: 'Responsable', cip: '' },
    },
    tasa: {
      materialBituminoso: '',
      gravedadEspecifica: '',
      loteProduccion: '',
      certificadoCalidad: '',
      temperaturaAtmosferica: '',
      temperaturaLigante: '',
    },
    tasaRegistroDatos: [
      {
        key: 'pesoBandejaConAsfalto',
        descripcion: '1. Peso de Bandeja con Asfalto',
        a: '',
        b: '',
        c: '',
        unidad: 'grs',
        observaciones: '',
      },
      {
        key: 'pesoBandejaSinAsfalto',
        descripcion: '2. Peso de Bandeja sin Asfalto',
        a: '',
        b: '',
        c: '',
        unidad: 'grs',
        observaciones: '',
      },
      {
        key: 'pesoAsfalto',
        descripcion: '3. Peso de Asfalto (1-2)',
        a: '',
        b: '',
        c: '',
        unidad: 'grs',
        observaciones: '',
        _computed: {
          a: 'rowValue("pesoBandejaConAsfalto", "a") && rowValue("pesoBandejaSinAsfalto", "a") ? round(rowValue("pesoBandejaConAsfalto", "a") - rowValue("pesoBandejaSinAsfalto", "a"), 0) : ""',
          b: 'rowValue("pesoBandejaConAsfalto", "b") && rowValue("pesoBandejaSinAsfalto", "b") ? round(rowValue("pesoBandejaConAsfalto", "b") - rowValue("pesoBandejaSinAsfalto", "b"), 0) : ""',
          c: 'rowValue("pesoBandejaConAsfalto", "c") && rowValue("pesoBandejaSinAsfalto", "c") ? round(rowValue("pesoBandejaConAsfalto", "c") - rowValue("pesoBandejaSinAsfalto", "c"), 0) : ""',
        },
      },
      {
        key: 'areaBandeja',
        descripcion: '4. Area de la Bandeja',
        a: '',
        b: '',
        c: '',
        unidad: 'cm2',
        observaciones: '',
      },
      {
        key: 'tasaRiego',
        descripcion: '5. Tasa de Riego (3/4)',
        a: '',
        b: '',
        c: '',
        unidad: 'grs/cm2',
        observaciones: '',
        _computed: {
          a: 'rowValue("pesoAsfalto", "a") && rowValue("areaBandeja", "a") ? round(rowValue("pesoAsfalto", "a") / rowValue("areaBandeja", "a"), 3) : ""',
          b: 'rowValue("pesoAsfalto", "b") && rowValue("areaBandeja", "b") ? round(rowValue("pesoAsfalto", "b") / rowValue("areaBandeja", "b"), 3) : ""',
          c: 'rowValue("pesoAsfalto", "c") && rowValue("areaBandeja", "c") ? round(rowValue("pesoAsfalto", "c") / rowValue("areaBandeja", "c"), 3) : ""',
        },
      },
      {
        key: 'tasaRiego10',
        descripcion: '6. Tasa de Riego (5 * 10)',
        a: '',
        b: '',
        c: '',
        unidad: 'kg/m2',
        observaciones: '',
        _computed: {
          a: 'rowValue("tasaRiego", "a") ? round(rowValue("tasaRiego", "a") * 10, 2) : ""',
          b: 'rowValue("tasaRiego", "b") ? round(rowValue("tasaRiego", "b") * 10, 2) : ""',
          c: 'rowValue("tasaRiego", "c") ? round(rowValue("tasaRiego", "c") * 10, 2) : ""',
        },
      },
      {
        key: 'tasaCorregida',
        descripcion: '7. Tasa Corregida (6 / a)',
        a: '',
        b: '',
        c: '',
        unidad: 'Lts/m2',
        observaciones: '',
        _computed: {
          a: 'rowValue("tasaRiego10", "a") && num(data.tasa?.gravedadEspecifica) ? round(rowValue("tasaRiego10", "a") / num(data.tasa?.gravedadEspecifica), 2) : ""',
          b: 'rowValue("tasaRiego10", "b") && num(data.tasa?.gravedadEspecifica) ? round(rowValue("tasaRiego10", "b") / num(data.tasa?.gravedadEspecifica), 2) : ""',
          c: 'rowValue("tasaRiego10", "c") && num(data.tasa?.gravedadEspecifica) ? round(rowValue("tasaRiego10", "c") / num(data.tasa?.gravedadEspecifica), 2) : ""',
        },
      },
      {
        key: 'tasaPromedio',
        descripcion: '8. Tasa Promedio del Riego de Liga',
        a: '',
        b: 0,
        c: '',
        unidad: 'Lts/m2',
        observaciones: '',
        _computed: {
          a: '""',
          b: 'rowValue("tasaCorregida", "a") || rowValue("tasaCorregida", "b") || rowValue("tasaCorregida", "c") ? round(avg([rowValue("tasaCorregida", "a") || null, rowValue("tasaCorregida", "b") || null, rowValue("tasaCorregida", "c") || null]), 2) : ""',
          c: '""',
        },
      },
      {
        key: 'criterioAceptacion',
        descripcion: '9. Criterio de aceptacion',
        a: '',
        b: '',
        c: '',
        unidad: 'Lts/m2',
        observaciones: '',
      },
    ],
    resultadoInspeccion: [
      {
        key: 'resultado',
        resultado:
          'El resultado final de la inspeccion cumple con los requerimientos indicados en las Especificaciones Tecnicas del proyecto',
        conforme: true,
        noConforme: false,
        nia: false,
        observaciones: 'NINGUNA',
      },
    ],
    observacionesTasa: '',
    firmasTasa: {
      elaboradoPor: { nombre: '', cargo: 'Responsable', cip: '' },
      revisadoPor: { nombre: '', cargo: 'Responsable', cip: '' },
      aprobadoPor: { nombre: '', cargo: 'Responsable', cip: '' },
    },
    registroFotografico: { fotos: [] },
  },
  exportOptions: {
    docx: true,
    pdf: true,
    excel: false,
  },
  normativeReference: [
    'EG-2013 MTC - Manual de Carreteras: Especificaciones Tecnicas Generales para Construccion',
  ],
};
