import { DocumentSchema } from './types';

export const cotizacionServicioSchema: DocumentSchema = {
  id: 'cotizacion-servicio',
  code: 'COT-SER',
  name: 'Cotización de Servicio',
  description: 'Documento comercial de cotización para servicios y obras.',
  category: 'Financial',
  version: '1.0.0',
  lastUpdated: '2026-03-26',
  orientation: 'portrait',
  pageSize: 'A4',
  margins: { top: 10, right: 10, bottom: 10, left: 10 },
  sections: [
    {
      id: 'header',
      type: 'header',
      headerConfig: {
        logoKey: 'header.logoUrl',
        leftTextKey: 'header.issuerName',
        centerLinesKeys: ['header.issuerAddress', 'header.issuerPhone', 'header.issuerRuc'],
        rightFields: [
          { label: 'COTIZACION', key: 'header.quoteNumber' },
          { label: 'FECHA', key: 'header.quoteDate' },
        ],
      },
    },
    {
      id: 'customer',
      type: 'simpleFields',
      title: 'Cliente',
      gridColumns: 4,
      fields: [
        { key: 'customer.name', label: 'CLIENTE', type: 'text', span: 12 },
        { key: 'customer.ruc', label: 'RUC', type: 'text', span: 6 },
        { key: 'customer.attention', label: 'ATT', type: 'text', span: 6 },
      ],
    },
    {
      id: 'intro',
      type: 'richText',
      title: 'Presentacion',
    },
    {
      id: 'items',
      type: 'dataTable',
      title: 'Detalle de Cotizacion',
      dynamicRows: true,
      minRows: 1,
      columns: [
        { key: 'itemCode', label: 'ITEM', type: 'text', width: 52, align: 'center' },
        { key: 'description', label: 'DESCRIPCION', type: 'text', width: 280, align: 'left' },
        { key: 'unit', label: 'UND.', type: 'text', width: 56, align: 'center' },
        { key: 'quantity', label: 'CANTIDAD', type: 'number', width: 72, align: 'right' },
        { key: 'unitPrice', label: 'P. UNIT.', type: 'currency', width: 86, align: 'right' },
        { key: 'lineTotal', label: 'TOTAL', type: 'currency', width: 86, align: 'right' },
      ],
    },
    {
      id: 'totals',
      type: 'simpleFields',
      title: 'Totales',
      gridColumns: 4,
      fields: [
        { key: 'totals.subtotal', label: 'SUBTOTAL', type: 'currency', span: 4 },
        { key: 'totals.igv', label: 'IGV', type: 'currency', span: 4 },
        { key: 'totals.total', label: 'TOTAL', type: 'currency', span: 4 },
      ],
    },
    {
      id: 'sections',
      type: 'simpleFields',
      title: 'Secciones',
      gridColumns: 2,
      fields: [],
    },
    {
      id: 'seller',
      type: 'simpleFields',
      title: 'Firma',
      gridColumns: 4,
      fields: [
        { key: 'seller.name', label: 'NOMBRE', type: 'text', span: 6 },
        { key: 'seller.role', label: 'CARGO', type: 'text', span: 6 },
      ],
    },
    {
      id: 'issuerBankAccounts',
      type: 'dataTable',
      title: 'Cuentas Bancarias',
      dynamicRows: true,
      minRows: 0,
      columns: [
        { key: 'bank', label: 'BANCO', type: 'text', width: 120, align: 'left' },
        { key: 'account', label: 'CUENTA', type: 'text', width: 140, align: 'left' },
        { key: 'cci', label: 'CCI', type: 'text', width: 190, align: 'left' },
        { key: 'type', label: 'TIPO', type: 'text', width: 120, align: 'left' },
      ],
    },
    {
      id: 'footer',
      type: 'simpleFields',
      title: 'Pie de Pagina',
      gridColumns: 4,
      fields: [
        { key: 'footer.address', label: 'DIRECCION', type: 'text', span: 6 },
        { key: 'footer.phone', label: 'TELEFONO', type: 'text', span: 3 },
        { key: 'footer.email', label: 'EMAIL', type: 'text', span: 3 },
      ],
    },
  ],
  defaultData: {
    header: {
      logoUrl: '',
      issuerName: '',
      issuerAddress: '',
      issuerPhone: '',
      issuerEmail: '',
      issuerRuc: '',
      quoteNumber: '',
      quoteDate: '',
    },
    customer: {
      name: '',
      ruc: '',
      attention: '',
    },
    intro: '',
    items: [],
    totals: {
      amountInWords: '',
      subtotal: 0,
      igv: 0,
      total: 0,
      currency: 'PEN',
    },
    sections: [],
    seller: {
      name: '',
      role: '',
      phone: '',
      email: '',
      signatureImageUrl: '',
    },
    issuerBankAccounts: [],
    footer: {
      address: '',
      phone: '',
      email: '',
      website: '',
    },
  },
  exportOptions: {
    pdf: true,
    docx: false,
    excel: false,
  },
};
