import { DocumentSchema } from './types';

/**
 * Schema para Informe de Area Adicional (IAA).
 * Documenta antecedentes, justificacion, ubicacion tecnica, metrado y panel fotografico.
 */
export const informeAreaAdicionalSchema: DocumentSchema = {
  id: 'informe-area-adicional',
  code: 'IAA',
  name: 'Informe de Area Adicional',
  description: 'Informe tecnico para metrado adicional y sustento en campo.',
  category: 'Operations',
  version: '1.0.0',
  lastUpdated: '2026-02-25',
  orientation: 'portrait',
  pageSize: 'A4',
  margins: { top: 15, right: 15, bottom: 15, left: 15 },
  sections: [
    {
      id: 'header',
      type: 'header',
      headerConfig: {
        logoKey: 'header.logoUrl',
        leftTextKey: 'header.companyName',
        centerLines: ['REGISTRO', 'CONTROL DE CALIDAD', 'INFORME DE AREA ADICIONAL'],
        rightFields: [
          { label: 'CODIGO', key: 'header.codigo' },
          { label: 'VERSION', key: 'header.version' },
          { label: 'FECHA', key: 'header.fecha' },
          { label: 'FOLIO', key: 'header.pagina' },
        ],
      },
    },
    {
      id: 'datosProyecto',
      type: 'projectData',
      title: 'Datos del Proyecto',
      gridColumns: 4,
      fields: [
        { key: 'proyecto.obra', label: 'OBRA', type: 'text', span: 4, required: true },
        { key: 'proyecto.cui', label: 'CODIGO UNICO (CUI)', type: 'text', span: 2 },
        { key: 'proyecto.entidad', label: 'ENTIDAD', type: 'text', span: 2 },
        { key: 'proyecto.contratista', label: 'CONTRATISTA', type: 'text', span: 2 },
        { key: 'proyecto.subcontratista', label: 'SUBCONTRATISTA', type: 'text', span: 2 },
        { key: 'proyecto.supervision', label: 'SUPERVISION', type: 'text', span: 2 },
        { key: 'proyecto.contrato', label: 'CONTRATO', type: 'text', span: 2 },
        { key: 'proyecto.ordenCompra', label: 'ORDEN DE COMPRA', type: 'text', span: 2 },
        { key: 'proyecto.ubicacion', label: 'UBICACION', type: 'text', span: 4 },
        { key: 'proyecto.frente', label: 'FRENTE', type: 'text', span: 2 },
      ],
    },
    {
      id: 'levantamientoTopografico',
      type: 'simpleFields',
      title: 'Datos del Levantamiento Topografico',
      gridColumns: 4,
      fields: [
        {
          key: 'levantamiento.incluir',
          label: 'INCLUIR DATOS DE LEVANTAMIENTO TOPOGRAFICO',
          type: 'checkbox',
          span: 4,
        },
        {
          key: 'levantamiento.topografo',
          label: 'TOPOGRAFO RESPONSABLE',
          type: 'text',
          span: 2,
          showIf: { field: 'levantamiento.incluir', operator: 'eq', value: true },
        },
        {
          key: 'levantamiento.cip',
          label: 'CIP',
          type: 'text',
          span: 2,
          showIf: { field: 'levantamiento.incluir', operator: 'eq', value: true },
        },
        {
          key: 'levantamiento.equipo',
          label: 'EQUIPO UTILIZADO',
          type: 'text',
          span: 2,
          showIf: { field: 'levantamiento.incluir', operator: 'eq', value: true },
        },
        {
          key: 'levantamiento.nroSerie',
          label: 'NRO SERIE',
          type: 'text',
          span: 2,
          showIf: { field: 'levantamiento.incluir', operator: 'eq', value: true },
        },
        {
          key: 'levantamiento.certCalibracion',
          label: 'CERT. CALIBRACION',
          type: 'text',
          span: 2,
          showIf: { field: 'levantamiento.incluir', operator: 'eq', value: true },
        },
        {
          key: 'levantamiento.fechaCalibracion',
          label: 'FECHA CALIBRACION',
          type: 'date',
          span: 2,
          showIf: { field: 'levantamiento.incluir', operator: 'eq', value: true },
        },
        {
          key: 'levantamiento.fechaLevantamiento',
          label: 'FECHA LEVANTAMIENTO',
          type: 'date',
          span: 2,
          showIf: { field: 'levantamiento.incluir', operator: 'eq', value: true },
        },
        {
          key: 'levantamiento.sistemaReferencia',
          label: 'SISTEMA REFERENCIA',
          type: 'text',
          span: 2,
          showIf: { field: 'levantamiento.incluir', operator: 'eq', value: true },
        },
        {
          key: 'levantamiento.planoReferencia',
          label: 'PLANO DE REFERENCIA',
          type: 'text',
          span: 4,
          showIf: { field: 'levantamiento.incluir', operator: 'eq', value: true },
        },
      ],
    },
    {
      id: 'antecedentes',
      type: 'richText',
      title: 'Antecedentes',
    },
    {
      id: 'justificacionTecnica',
      type: 'richText',
      title: 'Justificacion Tecnica',
    },
    {
      id: 'ubicacionTecnica',
      type: 'dataTable',
      title: 'Ubicacion Tecnica',
      dynamicRows: true,
      minRows: 1,
      maxRows: 200,
      columns: [
        { key: 'item', label: 'N°', type: 'text', width: 50, align: 'center', editable: true },
        { key: 'tramoZona', label: 'TRAMO / ZONA', type: 'text', width: 180, align: 'left', editable: true },
        { key: 'progInicial', label: 'PROG. INICIAL', type: 'text', width: 110, align: 'left', editable: true },
        { key: 'progFinal', label: 'PROG. FINAL', type: 'text', width: 110, align: 'left', editable: true },
        { key: 'lado', label: 'LADO', type: 'text', width: 90, align: 'left', editable: true },
        { key: 'descripcion', label: 'DESCRIPCION', type: 'text', width: 240, align: 'left', editable: true },
      ],
    },
    {
      id: 'cuadroMetrado',
      type: 'dataTable',
      title: 'Cuadro de Metrado',
      dynamicRows: true,
      minRows: 1,
      maxRows: 100,
      columns: [
        { key: 'item', label: 'ITEM', type: 'text', width: 60, align: 'center', editable: true, required: true },
        { key: 'partida', label: 'PARTIDA', type: 'text', width: 180, align: 'left', editable: true },
        { key: 'descripcion', label: 'DESCRIPCION', type: 'text', width: 220, align: 'left', editable: true, required: true },
        { key: 'unidad', label: 'UND', type: 'text', width: 60, align: 'center', editable: true },
        { key: 'metodo', label: 'METODO', type: 'text', width: 120, align: 'left', editable: true },
        { key: 'referencia', label: 'REFERENCIA', type: 'text', width: 140, align: 'left', editable: true },
        { key: 'area', label: 'AREA', type: 'number', width: 90, align: 'right', editable: true, decimals: 2 },
        { key: 'volumen', label: 'VOLUMEN', type: 'number', width: 90, align: 'right', editable: true, decimals: 2 },
      ],
    },
    {
      id: 'panelFotografico',
      type: 'photoPanel',
      title: 'Panel Fotografico',
      maxImages: 20,
      layout: '2x2',
      showProgresiva: true,
      showFecha: true,
      pageBreakBefore: true,
      includeHeader: true,
      headerOverride: {
        centerLines: ['REGISTRO', 'CONTROL DE CALIDAD', 'PANEL FOTOGRAFICO'],
      },
    },
    {
      id: 'conclusiones',
      type: 'richText',
      title: 'Conclusiones y Recomendaciones',
    },
    {
      id: 'firmas',
      type: 'signatures',
      title: 'Firmas de Conformidad',
      signatureStyle: 'line',
      signatures: [
        { key: 'elaboradoPor', label: 'ELABORADO POR', sublabel: 'Supervisor de Campo', required: true, showCIP: true },
        { key: 'revisadoPor', label: 'REVISADO POR', sublabel: 'Residente de Obra', required: false, showCIP: true },
        { key: 'aprobadoPor', label: 'APROBADO POR', sublabel: 'Residente de Obra', required: true, showCIP: true },
      ],
    },
  ],
  defaultData: {
    header: {
      logoUrl: '',
      companyName: '',
      codigo: '',
      version: '',
      fecha: '',
      pagina: '1-1',
      correlativo: '',
    },
    proyecto: {
      obra: '',
      cui: '',
      entidad: '',
      contratista: '',
      subcontratista: '',
      supervision: '',
      contrato: '',
      ordenCompra: '',
      ubicacion: '',
      frente: '',
    },
    levantamiento: {
      incluir: false,
      topografo: '',
      cip: '',
      equipo: '',
      nroSerie: '',
      certCalibracion: '',
      fechaCalibracion: '',
      fechaLevantamiento: '',
      sistemaReferencia: '',
      planoReferencia: '',
    },
    antecedentes: '',
    justificacionTecnica: '',
    ubicacionTecnica: [
      {
        item: '01',
        tramoZona: '',
        progInicial: '',
        progFinal: '',
        lado: '',
        descripcion: '',
      },
    ],
    cuadroMetrado: [
      {
        item: '01',
        partida: '',
        descripcion: '',
        unidad: '',
        metodo: '',
        referencia: '',
        area: 0,
        volumen: 0,
      },
    ],
    panelFotografico: {
      fotos: [],
    },
    conclusiones: '',
    firmas: {
      elaboradoPor: { nombre: '', cargo: 'Supervisor de Campo', cip: '' },
      revisadoPor: { nombre: '', cargo: 'Residente de Obra', cip: '' },
      aprobadoPor: { nombre: '', cargo: 'Residente de Obra', cip: '' },
    },
  },
  exportOptions: {
    docx: true,
    pdf: true,
    excel: false,
  },
};
