import { DocumentSchema } from './types';

/**
 * Schema para Informe de Area Adicional (IAA).
 * Documenta antecedentes, justificacion, ubicacion tecnica, metrado y panel fotografico.
 */
export const informeAreaAdicionalSchema: DocumentSchema = {
  id: 'informe-area-adicional',
  code: 'IAA',
  name: 'Informe de Area Adicional',
  description: 'Informe tecnico para metrado adicional y sustento en campo.',
  category: 'Operations',
  version: '1.0.0',
  lastUpdated: '2026-02-25',
  orientation: 'portrait',
  pageSize: 'A4',
  margins: { top: 15, right: 15, bottom: 15, left: 15 },
  sections: [
    {
      id: 'header',
      type: 'header',
      headerConfig: {
        logoKey: 'header.logoUrl',
        leftTextKey: 'header.companyName',
        centerLines: ['REGISTRO', 'CONTROL DE CALIDAD', 'INFORME DE AREA ADICIONAL'],
        rightFields: [
          { label: 'CODIGO', key: 'header.codigo' },
          { label: 'VERSION', key: 'header.version' },
          { label: 'FECHA', key: 'header.fecha' },
          { label: 'FOLIO', key: 'header.pagina' },
        ],
      },
    },
    {
      id: 'datosProyecto',
      type: 'projectData',
      title: 'Datos del Proyecto',
      gridColumns: 4,
      fields: [
        { key: 'proyecto.obra', label: 'OBRA', type: 'text', span: 4, required: true },
        { key: 'proyecto.entidad', label: 'ENTIDAD', type: 'text', span: 2 },
        { key: 'proyecto.contratista', label: 'CONTRATISTA', type: 'text', span: 2 },
        { key: 'proyecto.subcontratista', label: 'SUBCONTRATISTA', type: 'text', span: 2 },
        { key: 'proyecto.supervision', label: 'SUPERVISION', type: 'text', span: 2 },
      ],
    },
    {
      id: 'levantamientoTopografico',
      type: 'simpleFields',
      title: 'Datos del Levantamiento Topografico',
      gridColumns: 4,
      fields: [
        {
          key: 'levantamiento.incluir',
          label: 'INCLUIR DATOS DE LEVANTAMIENTO TOPOGRAFICO',
          type: 'checkbox',
          span: 4,
        },
        {
          key: 'levantamiento.topografo',
          label: 'TOPOGRAFO RESPONSABLE',
          type: 'text',
          span: 2,
          showIf: { field: 'levantamiento.incluir', operator: 'eq', value: true },
        },
        {
          key: 'levantamiento.cip',
          label: 'CIP',
          type: 'text',
          span: 2,
          showIf: { field: 'levantamiento.incluir', operator: 'eq', value: true },
        },
        {
          key: 'levantamiento.equipo',
          label: 'EQUIPO UTILIZADO',
          type: 'text',
          span: 2,
          showIf: { field: 'levantamiento.incluir', operator: 'eq', value: true },
        },
        {
          key: 'levantamiento.nroSerie',
          label: 'NRO SERIE',
          type: 'text',
          span: 2,
          showIf: { field: 'levantamiento.incluir', operator: 'eq', value: true },
        },
        {
          key: 'levantamiento.certCalibracion',
          label: 'CERT. CALIBRACION',
          type: 'text',
          span: 2,
          showIf: { field: 'levantamiento.incluir', operator: 'eq', value: true },
        },
        {
          key: 'levantamiento.fechaCalibracion',
          label: 'FECHA CALIBRACION',
          type: 'date',
          span: 2,
          showIf: { field: 'levantamiento.incluir', operator: 'eq', value: true },
        },
        {
          key: 'levantamiento.fechaLevantamiento',
          label: 'FECHA LEVANTAMIENTO',
          type: 'date',
          span: 2,
          showIf: { field: 'levantamiento.incluir', operator: 'eq', value: true },
        },
        {
          key: 'levantamiento.sistemaReferencia',
          label: 'SISTEMA REFERENCIA',
          type: 'text',
          span: 2,
          showIf: { field: 'levantamiento.incluir', operator: 'eq', value: true },
        },
        {
          key: 'levantamiento.planoReferencia',
          label: 'PLANO DE REFERENCIA',
          type: 'text',
          span: 4,
          showIf: { field: 'levantamiento.incluir', operator: 'eq', value: true },
        },
      ],
    },
    {
      id: 'objetoInforme',
      type: 'richText',
      title: 'Objeto del Informe',
    },
    {
      id: 'antecedentes',
      type: 'richText',
      title: 'Antecedentes',
    },
    {
      id: 'descripcionTrabajos',
      type: 'richText',
      title: 'Descripcion de los Trabajos Ejecutados',
    },
    {
      id: 'cuadroMetrado',
      type: 'dataTable',
      title: 'Cuadro Resumen de Metrados Adicionales (m2)',
      dynamicRows: true,
      minRows: 1,
      maxRows: 100,
      columns: [
        { key: 'item', label: 'Nro', type: 'text', width: 60, align: 'center', editable: true, required: true },
        { key: 'ubicacion', label: 'Ubicacion', type: 'text', width: 170, align: 'center', editable: true, required: true },
        { key: 'descripcion', label: 'Descripcion del Bacheo', type: 'text', width: 230, align: 'center', editable: true, required: true },
        { key: 'area', label: 'Area m2', type: 'number', width: 90, align: 'center', editable: true, decimals: 2 },
        { key: 'volumen', label: 'Volumen m3', type: 'number', width: 90, align: 'center', editable: true, decimals: 3 },
        { key: 'observaciones', label: 'Observaciones', type: 'text', width: 170, align: 'center', editable: true },
      ],
    },
    {
      id: 'panelFotografico',
      type: 'photoPanel',
      title: 'Panel Fotografico',
      maxImages: 20,
      layout: '2x2',
      showProgresiva: false,
      showFecha: false,
      pageBreakBefore: true,
      includeHeader: true,
      headerOverride: {
        centerLines: ['REGISTRO', 'CONTROL DE CALIDAD', 'PANEL FOTOGRAFICO'],
      },
    },
    {
      id: 'justificacionTecnica',
      type: 'richText',
      title: 'Justificacion Tecnica del Adicional',
    },
    {
      id: 'conclusiones',
      type: 'richText',
      title: 'Conclusiones y Recomendaciones',
    },
    {
      id: 'firmas',
      type: 'signatures',
      title: 'Firmas de Conformidad',
      signatureStyle: 'line',
      signatures: [
        { key: 'elaboradoPor', label: 'ELABORADO POR', sublabel: 'Supervisor de Campo', required: true, showCIP: true },
        { key: 'supervisadoPor', label: 'SUPERVISADO POR', sublabel: 'Residente de Obra', required: false, showCIP: true },
        { key: 'aprobadoPor', label: 'APROBADO POR', sublabel: 'Residente de Obra', required: true, showCIP: true },
      ],
    },
  ],
  defaultData: {
    header: {
      logoUrl: '',
      companyName: '',
      codigo: '',
      version: '',
      fecha: '',
      pagina: '1-1',
      correlativo: '',
    },
    proyecto: {
      obra: '',
      entidad: '',
      contratista: '',
      subcontratista: '',
      supervision: '',
    },
    levantamiento: {
      incluir: false,
      topografo: '',
      cip: '',
      equipo: '',
      nroSerie: '',
      certCalibracion: '',
      fechaCalibracion: '',
      fechaLevantamiento: '',
      sistemaReferencia: '',
      planoReferencia: '',
    },
    objetoInforme: 'El presente documento tiene por finalidad sustentar el adicional en los metrados de mezcla asfaltica ejecutados durante las labores de colocacion, bacheo o trabajos complementarios realizados en campo.\nEl incremento en metrados responde a la necesidad de corregir areas deterioradas, zonas con depresiones, fisuras, huecos estructurales u otras afectaciones detectadas durante la ejecucion.',
    antecedentes: 'La planta de asfalto fue convocada para la provision y colocacion de mezcla asfaltica en caliente.\nDurante la ejecucion se identificaron zonas no contempladas dentro del metrado original.\nComo parte del control de calidad y continuidad del servicio, se midieron las areas reales intervenidas y se registro evidencia fotografica.',
    descripcionTrabajos: 'Actividades realizadas:\n1. Inspeccion visual y determinacion de zonas deterioradas.\n2. Demarcacion de cada area a intervenir.\n3. Corte, limpieza y preparacion de superficie.\n4. Aplicacion de imprimante cuando corresponde.\n5. Colocacion y compactacion de mezcla asfaltica.\n6. Verificacion final de continuidad y nivelacion.',
    cuadroMetrado: [
      {
        item: '01',
        id: 'area-1',
        ubicacion: '',
        descripcion: 'Bacheo localizado',
        area: 0,
        volumen: 0,
        observaciones: '',
      },
    ],
    panelFotografico: {
      fotos: [],
    },
    justificacionTecnica: 'El adicional en area se justifica tecnica y operativamente por la presencia de base deteriorada, depresiones, fallas locales o condiciones reales de campo que requieren mayor intervencion para recuperar nivel, seguridad y calidad del acabado.',
    conclusiones: 'Los trabajos ejecutados en las zonas descritas superaron el metrado inicialmente programado por condiciones reales encontradas en campo.\nLas areas adicionales fueron medidas, registradas y documentadas con evidencia fotografica.\nEl metrado adicional total se solicita para evaluacion y aprobacion correspondiente.',
    firmas: {
      elaboradoPor: { nombre: '', cargo: 'Supervisor de Campo', cip: '' },
      supervisadoPor: { nombre: '', cargo: 'Residente de Obra', cip: '' },
      aprobadoPor: { nombre: '', cargo: 'Residente de Obra', cip: '' },
    },
  },
  exportOptions: {
    docx: true,
    pdf: true,
    excel: false,
  },
};
