import { DocumentSchema } from './types';

/**
 * Schema para Informe de Produccion de Planta (IPP).
 * Documenta el control de despachos de mezcla asfaltica en caliente.
 */
export const informeProduccionPlantaSchema: DocumentSchema = {
  id: 'informe-produccion-planta',
  code: 'IPP',
  name: 'Informe de Produccion de Planta',
  description: 'Control de despachos de mezcla asfaltica en caliente desde planta.',
  category: 'Operations',
  version: '1.0.0',
  lastUpdated: '2026-02-26',
  orientation: 'landscape',
  pageSize: 'A4',
  margins: { top: 15, right: 15, bottom: 15, left: 15 },
  sections: [
    {
      id: 'header',
      type: 'header',
      headerConfig: {
        logoKey: 'header.logoUrl',
        leftTextKey: 'header.companyName',
        centerLines: ['REGISTRO', 'CONTROL DE CALIDAD', 'INFORME DE PRODUCCION DE PLANTA'],
        rightFields: [
          { label: 'CODIGO', key: 'header.codigo' },
          { label: 'VERSION', key: 'header.version' },
          { label: 'FECHA', key: 'header.fecha' },
          { label: 'FOLIO', key: 'header.pagina' },
        ],
      },
    },
    {
      id: 'datosProyecto',
      type: 'projectData',
      title: 'I.A. Datos del Proyecto Destino',
      gridColumns: 4,
      fields: [
        { key: 'datosProyecto.obra', label: 'OBRA', type: 'text', span: 4, required: true },
        { key: 'datosProyecto.contratista', label: 'CONTRATISTA', type: 'text', span: 2 },
        { key: 'datosProyecto.subcontratista', label: 'SUB', type: 'text', span: 2 },
        { key: 'datosProyecto.frenteDestino', label: 'FRENTE / DESTINO', type: 'text', span: 2 },
        { key: 'datosProyecto.progresiva', label: 'PROGRESIVA', type: 'text', span: 2 },
      ],
    },
    {
      id: 'datosPlanta',
      type: 'simpleFields',
      title: 'I.B. Datos de la Planta de Asfalto',
      gridColumns: 4,
      fields: [
        { key: 'datosPlanta.planta', label: 'PLANTA', type: 'text', span: 4, required: true },
        { key: 'datosPlanta.ubicacion', label: 'UBICACION', type: 'text', span: 4 },
        { key: 'datosPlanta.tipoModelo', label: 'TIPO / MODELO', type: 'text', span: 2 },
        { key: 'datosPlanta.capacidad', label: 'CAPACIDAD', type: 'text', span: 2 },
        { key: 'datosPlanta.operadorEmpresa', label: 'OPERADOR (EMPRESA)', type: 'text', span: 2 },
        { key: 'datosPlanta.operadorRuc', label: 'RUC', type: 'text', span: 1 },
        { key: 'datosPlanta.operadorJefe', label: 'JEFE / RESPONSABLE', type: 'text', span: 3 },
      ],
    },
    {
      id: 'registroDespachos',
      type: 'dataTable',
      title: 'II. Registro de Despachos',
      dynamicRows: true,
      minRows: 0,
      maxRows: 100,
      columns: [
        { key: 'item', label: 'N°', type: 'number', width: 40, align: 'center', editable: false },
        { key: 'fecha', label: 'FECHA', type: 'date', width: 80, align: 'center', editable: true },
        { key: 'horaSalida', label: 'HORA SALIDA', type: 'time', width: 70, align: 'center', editable: true },
        { key: 'placa', label: 'PLACA', type: 'text', width: 70, align: 'center', editable: true },
        { key: 'chofer', label: 'CHOFER', type: 'text', width: 140, align: 'left', editable: true },
        { key: 'licencia', label: 'LICENCIA', type: 'text', width: 90, align: 'center', editable: true },
        { key: 'guiaRemision', label: 'GUIA REMISION', type: 'text', width: 100, align: 'center', editable: true },
        { key: 'nroCubos', label: 'N° CUBOS', type: 'number', width: 60, align: 'right', editable: true, decimals: 0 },
        { key: 'tempSalida', label: 'T° SAL. (°C)', type: 'number', width: 70, align: 'right', editable: true, decimals: 1 },
        {
          key: 'estado',
          label: 'ESTADO',
          type: 'select',
          width: 90,
          align: 'center',
          editable: true,
          options: [
            { value: 'CONFORME', label: 'CONFORME' },
            { value: 'OBSERVADO', label: 'OBSERVADO' },
            { value: 'RECHAZADO', label: 'RECHAZADO' },
          ],
        },
      ],
    },
    {
      id: 'resumenProduccion',
      type: 'simpleFields',
      title: 'III. Resumen de Produccion',
      gridColumns: 4,
      fields: [
        { key: 'resumenProduccion.totalDespachos', label: 'TOTAL DESPACHOS', type: 'number', span: 1, editable: false },
        { key: 'resumenProduccion.vehiculosUtilizados', label: 'VEHICULOS UTILIZADOS', type: 'number', span: 1, editable: false },
        { key: 'resumenProduccion.totalCubos', label: 'TOTAL CUBOS', type: 'number', span: 1, editable: false },
        { key: 'resumenProduccion.tempSalidaPromedio', label: 'TEMP. SALIDA PROMEDIO (°C)', type: 'number', span: 1, editable: false, decimals: 1 },
        { key: 'resumenProduccion.horarioProduccion', label: 'HORARIO PRODUCCION', type: 'text', span: 1, editable: false },
        { key: 'resumenProduccion.despachosConformes', label: 'DESPACHOS CONFORMES', type: 'number', span: 1, editable: false },
        { key: 'resumenProduccion.despachosObservados', label: 'DESPACHOS OBSERVADOS', type: 'number', span: 1, editable: false },
        { key: 'resumenProduccion.despachosRechazados', label: 'DESPACHOS RECHAZADOS', type: 'number', span: 1, editable: false },
      ],
    },
    {
      id: 'panelFotograficoPlanta',
      type: 'photoPanel',
      title: 'IV. Panel Fotografico de Planta',
      maxImages: 18,
      layout: '3x2',
      showProgresiva: false,
      showFecha: false,
      showHora: true,
      pageBreakBefore: true,
      includeHeader: true,
      headerOverride: {
        centerLines: ['REGISTRO', 'CONTROL DE CALIDAD', 'PANEL FOTOGRAFICO DE PLANTA'],
      },
      categories: [
        { key: 'PLANTA', label: 'PLANTA' },
        { key: 'CONTROL', label: 'CONTROL' },
        { key: 'CARGA', label: 'CARGA' },
        { key: 'DOCUMENTACION', label: 'DOCUMENTACION' },
      ],
    },
    {
      id: 'panelFotograficoLaboratorio',
      type: 'photoPanel',
      title: 'V. Panel Fotografico de Laboratorio',
      maxImages: 18,
      layout: '3x2',
      showProgresiva: false,
      showFecha: false,
      showHora: true,
      pageBreakBefore: true,
      includeHeader: true,
      headerOverride: {
        centerLines: ['REGISTRO', 'CONTROL DE CALIDAD', 'PANEL FOTOGRAFICO DE LABORATORIO'],
      },
      categories: [
        { key: 'MARSHALL', label: 'MARSHALL' },
        { key: 'EXTRACCION', label: 'EXTRACCION' },
        { key: 'GRANULOMETRIA', label: 'GRANULOMETRIA' },
        { key: 'RICE', label: 'RICE' },
      ],
    },
    {
      id: 'observaciones',
      type: 'richText',
      title: 'VI. Observaciones',
      pageBreakBefore: true,
    },
    {
      id: 'firmas',
      type: 'signatures',
      title: 'VII. Firmas de Conformidad',
      signatureStyle: 'line',
      signatures: [
        { key: 'jefePlanta', label: 'JEFE DE PLANTA', sublabel: 'Jefe de Produccion de Planta', required: true, showCIP: true },
        { key: 'laboratorista', label: 'LABORATORISTA', sublabel: 'Jefe de Laboratorio de Planta', required: false, showCIP: true },
        { key: 'controlCalidad', label: 'CONTROL DE CALIDAD', sublabel: 'Ing. Control de Calidad', required: true, showCIP: true },
      ],
    },
  ],
  defaultData: {
    header: {
      logoUrl: '',
      companyName: '',
      codigo: '',
      version: '',
      fecha: '',
      pagina: '1-1',
    },
    datosProyecto: {
      obra: '',
      contratista: '',
      subcontratista: '',
      frenteDestino: '',
      progresiva: '',
    },
    datosPlanta: {
      planta: '',
      ubicacion: '',
      tipoModelo: '',
      capacidad: '',
      operadorEmpresa: '',
      operadorRuc: '',
      operadorJefe: '',
    },
    registroDespachos: [],
    resumenProduccion: {
      totalDespachos: 0,
      vehiculosUtilizados: 0,
      totalCubos: 0,
      tempSalidaPromedio: 0,
      horarioProduccion: '',
      despachosConformes: 0,
      despachosObservados: 0,
      despachosRechazados: 0,
    },
    panelFotograficoPlanta: {
      fotos: [],
    },
    panelFotograficoLaboratorio: {
      fotos: [],
    },
    observaciones: '',
    firmas: {
      jefePlanta: { nombre: '', cargo: 'Jefe de Produccion de Planta', empresa: '', cip: '' },
      laboratorista: { nombre: '', cargo: 'Jefe de Laboratorio de Planta', empresa: '', cip: '' },
      controlCalidad: { nombre: '', cargo: 'Ing. Control de Calidad', empresa: '', cip: '' },
    },
  },
  exportOptions: {
    docx: true,
    pdf: true,
    excel: false,
  },
};
