import { DocumentSchema } from './types';

export const liquidacionServicioSchema: DocumentSchema = {
  id: 'liquidacion-servicio',
  code: 'LIQ-SRV',
  name: 'Liquidacion Final del Servicio',
  description: 'Liquidacion final con cotizacion, pagos, ejecutado y saldo.',
  category: 'Financial',
  version: '1.0.0',
  lastUpdated: '2026-05-19',
  orientation: 'portrait',
  pageSize: 'A4',
  margins: { top: 20, right: 12, bottom: 18, left: 12 },
  sections: [
    {
      id: 'header',
      type: 'header',
      headerConfig: {
        logoKey: 'header.logoUrl',
        leftTextKey: 'header.companyName',
        centerLines: ['REGISTRO', 'LIQUIDACION FINAL DEL SERVICIO'],
        rightFields: [
          { label: 'CODIGO', key: 'header.codigo' },
          { label: 'VERSION', key: 'header.version' },
          { label: 'FECHA', key: 'header.fecha' },
          { label: 'FOLIO', key: 'header.pagina' },
        ],
      },
    },
    {
      id: 'datosGenerales',
      type: 'simpleFields',
      title: 'Datos Generales',
      gridColumns: 4,
      fields: [
        { key: 'proyecto.obra', label: 'PROYECTO', type: 'text', span: 12 },
        { key: 'proyecto.contratista', label: 'CONTRATISTA', type: 'text', span: 6 },
        { key: 'proyecto.contratistaRuc', label: 'RUC CONTRATISTA', type: 'text', span: 6 },
        { key: 'proyecto.proveedor', label: 'PROVEEDOR DEL SERVICIO', type: 'text', span: 6 },
        { key: 'proyecto.proveedorRuc', label: 'RUC PROVEEDOR', type: 'text', span: 6 },
        { key: 'proyecto.servicio', label: 'SERVICIO', type: 'text', span: 12 },
      ],
    },
    {
      id: 'cotizacionInicial',
      type: 'dataTable',
      title: 'Monto Cotizacion Inicial',
      dynamicRows: true,
      minRows: 0,
      showTotals: false,
      columns: [
        { key: 'item', label: 'ITEM', type: 'text', width: 70, align: 'center', editable: true },
        { key: 'descripcion', label: 'DESCRIPCION', type: 'text', width: 280, align: 'left', editable: true },
        { key: 'unidad', label: 'UNID', type: 'text', width: 60, align: 'center', editable: true },
        { key: 'metrado', label: 'METRADO', type: 'number', width: 90, align: 'right', editable: true },
        { key: 'precioUnitario', label: 'PRECIO UNIT.', type: 'currency', width: 100, align: 'right', editable: true },
        { key: 'parcial', label: 'P. PARCIAL', type: 'currency', width: 110, align: 'right', editable: true },
      ],
    },
    {
      id: 'pagos',
      type: 'dataTable',
      title: 'Monto Pagado',
      dynamicRows: true,
      minRows: 0,
      showTotals: false,
      columns: [
        { key: 'fecha', label: 'FECHA', type: 'date', width: 90, align: 'center', editable: true },
        { key: 'operacion', label: 'N OPERACION', type: 'text', width: 140, align: 'center', editable: true },
        { key: 'destinatario', label: 'CUENTA DESTINATARIO', type: 'text', width: 260, align: 'left', editable: true },
        { key: 'monto', label: 'MONTO', type: 'currency', width: 120, align: 'right', editable: true },
      ],
    },
    {
      id: 'montoEjecutado',
      type: 'dataTable',
      title: 'Monto Ejecutado',
      dynamicRows: true,
      minRows: 0,
      showTotals: false,
      columns: [
        { key: 'item', label: 'ITEM', type: 'text', width: 70, align: 'center', editable: true },
        { key: 'descripcion', label: 'DESCRIPCION', type: 'text', width: 280, align: 'left', editable: true },
        { key: 'unidad', label: 'UNID', type: 'text', width: 60, align: 'center', editable: true },
        { key: 'metrado', label: 'METRADO', type: 'number', width: 90, align: 'right', editable: true },
        { key: 'precioUnitario', label: 'PRECIO UNIT.', type: 'currency', width: 100, align: 'right', editable: true },
        { key: 'parcial', label: 'P. PARCIAL', type: 'currency', width: 110, align: 'right', editable: true },
      ],
    },
    {
      id: 'saldo',
      type: 'simpleFields',
      title: 'Monto o Saldo por Pagar',
      gridColumns: 4,
      fields: [
        { key: 'saldo.montoEjecutado', label: 'MONTO EJECUTADO', type: 'currency', span: 4 },
        { key: 'saldo.montoPagado', label: 'MONTO PAGADO', type: 'currency', span: 4 },
        { key: 'saldo.saldoPorPagar', label: 'SALDO POR PAGAR', type: 'currency', span: 4 },
      ],
    },
    {
      id: 'vouchers',
      type: 'photoPanel',
      title: 'Panel Fotografico de Vouchers',
      maxImages: 24,
      layout: '2x2',
      showFecha: true,
    },
    {
      id: 'observaciones',
      type: 'richText',
      title: 'Observaciones',
    },
    {
      id: 'firmas',
      type: 'signatures',
      title: 'Firmas',
      signatureStyle: 'line',
      signatures: [
        { key: 'elaboradoPor', label: 'ELABORADO POR', sublabel: 'Responsable', showCIP: true },
        { key: 'aprobadoPor', label: 'APROBADO POR', sublabel: 'Representante', showCIP: true },
      ],
    },
  ],
  defaultData: {
    header: {
      logoUrl: '',
      companyName: '',
      codigo: '',
      version: '',
      fecha: '',
      pagina: '1-1',
      correlativo: '',
    },
    proyecto: {
      obra: '',
      contratista: '',
      contratistaRuc: '',
      proveedor: '',
      proveedorRuc: '',
      servicio: '',
    },
    cotizacionInicial: [],
    pagos: [],
    montoEjecutado: [],
    saldo: {
      montoEjecutado: 0,
      montoPagado: 0,
      saldoPorPagar: 0,
    },
    vouchers: { fotos: [] },
    observaciones: '',
    firmas: {},
  },
  exportOptions: {
    pdf: true,
    docx: false,
    excel: false,
  },
};
