import { DocumentSchema } from './types';

export const ordenCompraSchema: DocumentSchema = {
  id: 'orden-compra',
  code: 'ORD-COM',
  name: 'Orden de Compra',
  description: 'Documento comercial de orden de compra para adquisiciones.',
  category: 'Financial',
  version: '1.0.0',
  lastUpdated: '2026-03-28',
  orientation: 'portrait',
  pageSize: 'A4',
  margins: { top: 10, right: 10, bottom: 10, left: 10 },
  sections: [
    {
      id: 'header',
      type: 'header',
      headerConfig: {
        logoKey: 'header.logoUrl',
        leftTextKey: 'header.issuerName',
        centerLinesKeys: ['header.issuerAddress', 'header.issuerRuc'],
        rightFields: [
          { label: 'ORDEN DE COMPRA', key: 'header.orderNumber' },
          { label: 'FECHA', key: 'header.orderDate' },
        ],
      },
    },
    {
      id: 'supplier',
      type: 'simpleFields',
      title: 'Proveedor',
      gridColumns: 4,
      fields: [
        { key: 'supplier.ruc', label: 'RUC', type: 'text', span: 4 },
        { key: 'supplier.name', label: 'RAZON SOCIAL', type: 'text', span: 8 },
        { key: 'supplier.address', label: 'DIRECCION', type: 'text', span: 12 },
      ],
    },
    {
      id: 'meta',
      type: 'simpleFields',
      title: 'Datos de Orden',
      gridColumns: 4,
      fields: [
        { key: 'meta.paymentMethod', label: 'FORMA DE PAGO', type: 'text', span: 4 },
        { key: 'meta.currencyLabel', label: 'MONEDA', type: 'text', span: 4 },
        { key: 'meta.project', label: 'PROYECTO', type: 'text', span: 4 },
        { key: 'meta.exchangeRateUsed', label: 'TIPO DE CAMBIO', type: 'number', span: 4 },
        { key: 'meta.totalInSoles', label: 'TOTAL EN SOLES', type: 'currency', span: 4 },
      ],
    },
    {
      id: 'items',
      type: 'dataTable',
      title: 'Detalle',
      dynamicRows: true,
      minRows: 1,
      columns: [
        { key: 'itemCode', label: 'ITEM', type: 'text', width: 48, align: 'center' },
        { key: 'description', label: 'DESCRIPCION', type: 'text', width: 280, align: 'left' },
        { key: 'unit', label: 'UND.', type: 'text', width: 58, align: 'center' },
        { key: 'quantity', label: 'CANT.', type: 'number', width: 70, align: 'right' },
        { key: 'unitPrice', label: 'P. UNIT.', type: 'currency', width: 86, align: 'right' },
        { key: 'lineTotal', label: 'TOTAL', type: 'currency', width: 86, align: 'right' },
      ],
    },
    {
      id: 'totals',
      type: 'simpleFields',
      title: 'Totales',
      gridColumns: 4,
      fields: [
        { key: 'totals.amountInWords', label: 'SON', type: 'text', span: 12 },
        { key: 'totals.subtotal', label: 'SUBTOTAL', type: 'currency', span: 4 },
        { key: 'totals.igv', label: 'IGV', type: 'currency', span: 4 },
        { key: 'totals.total', label: 'TOTAL', type: 'currency', span: 4 },
      ],
    },
    {
      id: 'bankAccounts',
      type: 'dataTable',
      title: 'Cuentas Bancarias',
      dynamicRows: true,
      minRows: 0,
      columns: [
        { key: 'bank', label: 'BANCO', type: 'text', width: 120, align: 'left' },
        { key: 'account', label: 'CUENTA', type: 'text', width: 150, align: 'left' },
        { key: 'cci', label: 'CCI', type: 'text', width: 190, align: 'left' },
        { key: 'type', label: 'TIPO', type: 'text', width: 120, align: 'left' },
      ],
    },
    {
      id: 'seller',
      type: 'simpleFields',
      title: 'Aprobacion',
      gridColumns: 4,
      fields: [
        { key: 'seller.name', label: 'NOMBRE', type: 'text', span: 6 },
        { key: 'seller.role', label: 'CARGO', type: 'text', span: 6 },
      ],
    },
    {
      id: 'observations',
      type: 'richText',
      title: 'Observaciones',
    },
  ],
  defaultData: {
    header: {
      logoUrl: '',
      issuerName: '',
      issuerRuc: '',
      issuerAddress: '',
      orderNumber: '',
      orderDate: '',
    },
    supplier: {
      ruc: '',
      name: '',
      address: '',
    },
    meta: {
      paymentMethod: '',
      currencyLabel: '',
      currencyCode: 'PEN',
      project: '',
      exchangeRateUsed: undefined,
      totalInSoles: undefined,
    },
    items: [],
    totals: {
      subtotal: 0,
      igv: 0,
      total: 0,
      amountInWords: '',
      currencyCode: 'PEN',
      currencyLabel: '',
      totalInSoles: undefined,
    },
    termsText: '',
    observations: '',
    bankAccounts: [],
    seller: {
      name: '',
      role: '',
      includeSignature: true,
      signatureImageUrl: '',
    },
    footer: {
      issuerName: '',
      issuerRuc: '',
    },
  },
  exportOptions: {
    pdf: true,
    docx: false,
    excel: false,
  },
};
